### ISSUE TITLE
doesn't find media thumbnails on youtube rss feed

### ISSUE THREAD

**Issue by sgehrman** [ubuntu-flutter-community/rss.dart#5]
https://www.youtube.com/feeds/videos.xml?channel_id=UCnCikd0s4i9KoDtaHPlK-JA

**Comment by sgehrman** [comment]
this doesn't work.  element.findElements('media:thumbnail');

this works.  element.findAllElements('media:thumbnail');

Is this a bug? or is youtube different?

**Comment by sgehrman** [comment]
maybe this is a fix?

https://github.com/michael-yarzebinski/rss.dart/commit/a8d3c34f553f7ea29ac993bb22500e4b9f4f3274

**Comment by amugofjava** [comment]
Fixed by PR. Thank you.
