### ISSUE TITLE
use lints and fix the problems

### ISSUE THREAD

**Issue by sgehrman** [ubuntu-flutter-community/rss.dart#7]
[{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/dart_rss.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'RSS1' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 30,
	"startColumn": 3,
	"endLineNumber": 30,
	"endColumn": 7
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/dart_rss.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'RSS2' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 31,
	"startColumn": 3,
	"endLineNumber": 31,
	"endColumn": 7
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/dart_rss.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'Atom' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 32,
	"startColumn": 3,
	"endLineNumber": 32,
	"endColumn": 7
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/dart_rss.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'Unknown' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 33,
	"startColumn": 3,
	"endLineNumber": 33,
	"endColumn": 10
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/rss1_feed.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'Hourly' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 9,
	"startColumn": 3,
	"endLineNumber": 9,
	"endColumn": 9
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/rss1_feed.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'Daily' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 10,
	"startColumn": 3,
	"endLineNumber": 10,
	"endColumn": 8
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/rss1_feed.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'Weekly' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 11,
	"startColumn": 3,
	"endLineNumber": 11,
	"endColumn": 9
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/rss1_feed.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'Monthly' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 12,
	"startColumn": 3,
	"endLineNumber": 12,
	"endColumn": 10
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/lib/domain/rss1_feed.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "constant_identifier_names",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/constant_identifier_names",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The constant name 'Yearly' isn't a lowerCamelCase identifier.\nTry changing the name to follow the lowerCamelCase style.",
	"source": "dart",
	"startLineNumber": 13,
	"startColumn": 3,
	"endLineNumber": 13,
	"endColumn": 9
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_string_escapes",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_string_escapes",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary escape in string literal.\nRemove the '\\' escape.",
	"source": "dart",
	"startLineNumber": 101,
	"startColumn": 41,
	"endLineNumber": 101,
	"endColumn": 42
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_string_escapes",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_string_escapes",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary escape in string literal.\nRemove the '\\' escape.",
	"source": "dart",
	"startLineNumber": 101,
	"startColumn": 47,
	"endLineNumber": 101,
	"endColumn": 48
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_string_escapes",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_string_escapes",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary escape in string literal.\nRemove the '\\' escape.",
	"source": "dart",
	"startLineNumber": 101,
	"startColumn": 57,
	"endLineNumber": 101,
	"endColumn": 58
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_string_escapes",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_string_escapes",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary escape in string literal.\nRemove the '\\' escape.",
	"source": "dart",
	"startLineNumber": 101,
	"startColumn": 62,
	"endLineNumber": 101,
	"endColumn": 63
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_string_escapes",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_string_escapes",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary escape in string literal.\nRemove the '\\' escape.",
	"source": "dart",
	"startLineNumber": 101,
	"startColumn": 69,
	"endLineNumber": 101,
	"endColumn": 70
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_string_escapes",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_string_escapes",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary escape in string literal.\nRemove the '\\' escape.",
	"source": "dart",
	"startLineNumber": 101,
	"startColumn": 98,
	"endLineNumber": 101,
	"endColumn": 99
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "require_trailing_commas",
		"target": {
			"$mid": 1,
			"path": "/lints/require_trailing_commas",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Missing a required trailing comma.",
	"source": "dart",
	"startLineNumber": 442,
	"startColumn": 37,
	"endLineNumber": 442,
	"endColumn": 38
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "require_trailing_commas",
		"target": {
			"$mid": 1,
			"path": "/lints/require_trailing_commas",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Missing a required trailing comma.",
	"source": "dart",
	"startLineNumber": 446,
	"startColumn": 78,
	"endLineNumber": 446,
	"endColumn": 79
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "require_trailing_commas",
		"target": {
			"$mid": 1,
			"path": "/lints/require_trailing_commas",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Missing a required trailing comma.",
	"source": "dart",
	"startLineNumber": 449,
	"startColumn": 37,
	"endLineNumber": 449,
	"endColumn": 38
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "require_trailing_commas",
		"target": {
			"$mid": 1,
			"path": "/lints/require_trailing_commas",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Missing a required trailing comma.",
	"source": "dart",
	"startLineNumber": 472,
	"startColumn": 49,
	"endLineNumber": 472,
	"endColumn": 50
},{
	"resource": "/home/steve/Documents/GitHub/dfc/forks/rss.dart/test/rss_test.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "require_trailing_commas",
		"target": {
			"$mid": 1,
			"path": "/lints/require_trailing_commas",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Missing a required trailing comma.",
	"source": "dart",
	"startLineNumber": 592,
	"startColumn": 81,
	"endLineNumber": 592,
	"endColumn": 82
}]

**Comment by amugofjava** [comment]
Issue already raised as #6. If you want to add more information, please comment on the open issue rather than raising another issue. It makes it more complicated for the maintainers.
